"""init schema

Revision ID: a5a43b9b812b
Revises: 
Create Date: 2026-05-25 14:06:31.791546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a43b9b812b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_analytics_metric_date', ['metric_date'], unique=False)
        batch_op.create_index('idx_analytics_metric_name', ['metric_name'], unique=False)

    op.create_table('inference_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inference_logs', schema=None) as batch_op:
        batch_op.create_index('idx_inference_logs_status', ['status'], unique=False)
        batch_op.create_index('idx_inference_logs_time', ['created_at'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geojson', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('idx_locations_geo', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('idx_locations_region', ['region'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('framework', sa.String(length=60), nullable=True),
    sa.Column('artifact_path', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_version')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('vegetation', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.create_index('idx_weather_geo', ['lat', 'lon'], unique=False)
        batch_op.create_index('idx_weather_time', ['observed_at'], unique=False)

    op.create_table('alert_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_recipients', schema=None) as batch_op:
        batch_op.create_index('idx_alert_recipients_channel', ['channel'], unique=False)

    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index('idx_analytics_events_time', ['event_time'], unique=False)
        batch_op.create_index('idx_analytics_events_type', ['event_type'], unique=False)

    op.create_table('export_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('export_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.create_index('idx_export_history_status', ['status'], unique=False)
        batch_op.create_index('idx_export_history_time', ['requested_at'], unique=False)

    op.create_table('historical_wildfires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(length=40), nullable=True),
    sa.Column('burned_area_ha', sa.Float(), nullable=True),
    sa.Column('cause', sa.String(length=120), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_wildfires', schema=None) as batch_op:
        batch_op.create_index('idx_historical_wildfires_location', ['location_id'], unique=False)
        batch_op.create_index('idx_historical_wildfires_time', ['started_at'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('raw_features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('idx_predictions_location_time', ['location_id', 'predicted_at'], unique=False)
        batch_op.create_index('idx_predictions_model', ['model_version_id'], unique=False)

    op.create_table('risk_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('weather_observation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weather_observation_id'], ['weather_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.create_index('idx_predictions_geo', ['lat', 'lon'], unique=False)
        batch_op.create_index('idx_predictions_time', ['created_at'], unique=False)

    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index('idx_risk_scores_location_time', ['location_id', 'scored_at'], unique=False)

    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.create_index('idx_user_activity_time', ['occurred_at'], unique=False)

    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_mps', sa.Float(), nullable=True),
    sa.Column('wind_dir_deg', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_records', schema=None) as batch_op:
        batch_op.create_index('idx_weather_records_location_time', ['location_id', 'observed_at'], unique=False)

    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index('idx_ai_insights_prediction', ['prediction_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_predictions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alerts_status', ['status'], unique=False)
        batch_op.create_index('idx_alerts_time', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alerts_time')
        batch_op.drop_index('idx_alerts_status')

    op.drop_table('alerts')
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_insights_prediction')

    op.drop_table('ai_insights')
    with op.batch_alter_table('weather_records', schema=None) as batch_op:
        batch_op.drop_index('idx_weather_records_location_time')

    op.drop_table('weather_records')
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_index('idx_user_activity_time')

    op.drop_table('user_activity')
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index('idx_risk_scores_location_time')

    op.drop_table('risk_scores')
    with op.batch_alter_table('risk_predictions', schema=None) as batch_op:
        batch_op.drop_index('idx_predictions_time')
        batch_op.drop_index('idx_predictions_geo')

    op.drop_table('risk_predictions')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('idx_predictions_model')
        batch_op.drop_index('idx_predictions_location_time')

    op.drop_table('predictions')
    with op.batch_alter_table('historical_wildfires', schema=None) as batch_op:
        batch_op.drop_index('idx_historical_wildfires_time')
        batch_op.drop_index('idx_historical_wildfires_location')

    op.drop_table('historical_wildfires')
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.drop_index('idx_export_history_time')
        batch_op.drop_index('idx_export_history_status')

    op.drop_table('export_history')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_events_type')
        batch_op.drop_index('idx_analytics_events_time')

    op.drop_table('analytics_events')
    with op.batch_alter_table('alert_recipients', schema=None) as batch_op:
        batch_op.drop_index('idx_alert_recipients_channel')

    op.drop_table('alert_recipients')
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_index('idx_weather_time')
        batch_op.drop_index('idx_weather_geo')

    op.drop_table('weather_observations')
    op.drop_table('users')
    op.drop_table('model_versions')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('idx_locations_region')
        batch_op.drop_index('idx_locations_geo')

    op.drop_table('locations')
    with op.batch_alter_table('inference_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_inference_logs_time')
        batch_op.drop_index('idx_inference_logs_status')

    op.drop_table('inference_logs')
    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_metric_name')
        batch_op.drop_index('idx_analytics_metric_date')

    op.drop_table('analytics_metrics')
    # ### end Alembic commands ###
